repos:
- repo: local
  hooks: []
  # hooks:
  # - id: ruff-check
  #   name: ruff-check
  #   entry: uv run python -m ruff check .
  #   language: python
  #   types: [ python ]
  #   additional_dependencies: [ uv ]