name: Update AoC Badges
on:
  schedule:                                      # run workflow based on schedule
    - cron: '6 5 1-13 12 *'                      # from the 1. December till 13. December every day at 5:06am (avoid load at full hours)

  workflow_dispatch:                             # allow to manually start the workflow

# push:                                          # (disabled) run on push, be carefull with this setting
                                                 # as the workflow should only be triggered at a rate lower than
                                                 # 4 times a hour to keep traffic on aoc site low
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                # clones your repo

      - name: Pull latest changes                # Updates repo to latest version to avoid conflicts
        run: git pull origin ${{ github.ref }}

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2019                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2019/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2019_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2019_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.


      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2020                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2020_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2020_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.


      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2021                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2021/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2022                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2022/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2023                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2023/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2023_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2023_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2024                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2024/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2024_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2024_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1439540                          # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          year: 2025                                                                                     # The year for which stats should be retrieved
          leaderboard: 'https://adventofcode.com/2025/leaderboard/private/view/1439540.json'               # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          file: 'README.md'                                                                              # The file that contains the badges
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2025_stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2025_days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - uses: stefanzweifel/git-auto-commit-action@v4     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md
